name: Access ID Workflow

on:
  push:

jobs:
  print-access-id:
    name: Print ACCESS_ID Job
    runs-on: ubuntu-latest  # ✅ Ensures it's explicitly specified

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print ACCESS_ID from repository variable
        run: echo "The ACCESS_ID is \${{ vars.ACCESS_ID }}"

